# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  
  config.vm.define "logbox" do |logbox|
    # https://vagrantcloud.com/zauberpony/wheezy64
    logbox.vm.box = "zauberpony/wheezy64"
    logbox.vm.box_check_update = false
  
    # https://coderwall.com/p/qtbi5a
    logbox.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"  
    logbox.vm.provision "shell", path: "bootstrap.sh"

    # Apache
    logbox.vm.network "forwarded_port", guest: 80,    host: 9090
  
    # Graphite
    logbox.vm.network "forwarded_port", guest: 2003,  host: 2003
  
    # ElasticSearch
    logbox.vm.network "forwarded_port", guest: 9200,  host: 9200

    # Logstash
    logbox.vm.network "forwarded_port", guest: 5000,  host: 5000
    logbox.vm.network "private_network", ip: "192.168.100.10"
  end

end
